# Generated by Django 4.2.7 on 2024-06-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("ARS", "Arsenal"),
                            ("CHE", "Chelsea"),
                            ("LIV", "Liverpool"),
                            ("MCI", "Manchester City"),
                            ("MUN", "Manchester United"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("2021/2022", "2021/2022"),
                            ("2022/2023", "2022/2023"),
                            ("2023/2024", "2023/2024"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "home_or_away",
                    models.CharField(
                        choices=[
                            ("Home", "Home"),
                            ("Away", "Away"),
                            ("Third", "Third"),
                        ],
                        max_length=5,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="shirts/")),
                ("stock", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
