# Generated by Django 4.2.7 on 2024-06-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='sku',
            field=models.CharField(default='DEFAULT-SKU', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
