# Generated by Django 4.2.7 on 2024-06-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shirts", "0002_shirt_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="shirt",
            name="type",
            field=models.CharField(
                choices=[("Home", "Home"), ("Away", "Away"), ("Third", "Third")],
                default="home",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
