# Generated by Django 4.2.7 on 2024-12-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0006_alter_shirt_season_alter_shirt_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
